---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tape2497/vacances.teodul.fr/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R javascript $DEPLOYPATH
    - /bin/cp -R i18n $DEPLOYPATH
    - /bin/cp -R html/* $DEPLOYPATH
